export const popular = [
  {
    name: "Fullmetal Alchemist: Brotherhood",
    category: "Anime",
    director: "Yasuhiro Irie",
    duration: "24 min per episode",
    year_of_publishing: 2009,
    rating: 5,
    tags: ["Action", "Adventure", "Fantasy"],
    product_id: "005",
    price: 34.99,
    image: "https://i.ibb.co.com/VC7Pn6w/product12-copyright-600x700.jpg",
    description:
      "Two brothers use alchemy to find the Philosopher's Stone to restore their bodies.",
  },
  {
    name: "Death Note",
    category: "Anime",
    director: "Tetsurō Araki",
    duration: "23 min per episode",
    year_of_publishing: 2006,
    rating: 4.5,
    tags: ["Psychological", "Thriller", "Supernatural"],
    product_id: "006",
    price: 29.99,
    image: "https://i.ibb.co.com/jHXP4W4/product13-copyright-600x700.jpg",
    description:
      "A high school student discovers a supernatural notebook that allows him to kill anyone.",
  },
  {
    name: "Sword Art Online",
    category: "Anime",
    director: "Tomohiko Itō",
    duration: "23 min per episode",
    year_of_publishing: 2012,
    rating: 4,
    tags: ["Action", "Adventure", "Romance"],
    product_id: "007",
    price: 27.99,
    image: "https://i.ibb.co.com/wRWjs0w/product14-copyright-600x700.jpg",
    description:
      "Thousands of players are trapped in a new virtual MMORPG, and their only way out is to clear the game.",
  },
  {
    name: "Jujutsu Kaisen",
    category: "Anime",
    director: "Sunghoo Park",
    duration: "23 min per episode",
    year_of_publishing: 2020,
    rating: 5,
    tags: ["Action", "Supernatural", "Dark Fantasy"],
    product_id: "008",
    price: 31.99,
    image: "https://i.ibb.co.com/S5bRwNs/product15-copyright-600x700.jpg",
    description:
      "Yuji Itadori joins a secret organization to protect the world from curses after becoming the host of a powerful curse.",
  },
  {
    name: "Tokyo Ghoul",
    category: "Anime",
    director: "Shuhei Morita",
    duration: "24 min per episode",
    year_of_publishing: 2014,
    rating: 4.5,
    tags: ["Action", "Supernatural", "Horror"],
    product_id: "009",
    price: 26.99,
    image: "https://i.ibb.co.com/kGfJBKx/product16-copyright-600x700.jpg",
    description:
      "An ordinary college student is turned into a half-ghoul and must learn to live in both worlds.",
  },
  {
    name: "My Hero Academia",
    category: "Anime",
    director: "Kenji Nagasaki",
    duration: "24 min per episode",
    year_of_publishing: 2016,
    rating: 5,
    tags: ["Action", "Superhero", "Fantasy"],
    product_id: "010",
    price: 32.99,
    image: "https://i.ibb.co.com/vXdQX2z/product17-copyright-600x700.jpg",
    description:
      "In a world where nearly everyone has superpowers, a powerless boy enrolls in a hero academy to become a true hero.",
  },
];
