export const shop = [
  {
    name: "Fullmetal Alchemist: Brotherhood",
    category: "Anime",
    director: "Yasuhiro Irie",
    duration: "24 min per episode",
    year_of_publishing: 2009,
    rating: 5,
    tags: ["Action", "Adventure", "Fantasy"],
    product_id: "005",
    price: 34.99,
    image: "https://i.ibb.co.com/VC7Pn6w/product12-copyright-600x700.jpg",
    description:
      "Two brothers use alchemy to find the Philosopher's Stone to restore their bodies.",
  },
  {
    name: "Death Note",
    category: "Anime",
    director: "Tetsurō Araki",
    duration: "23 min per episode",
    year_of_publishing: 2006,
    rating: 4.5,
    tags: ["Psychological", "Thriller", "Supernatural"],
    product_id: "006",
    price: 29.99,
    image: "https://i.ibb.co.com/jHXP4W4/product13-copyright-600x700.jpg",
    description:
      "A high school student discovers a supernatural notebook that allows him to kill anyone.",
  },
  {
    name: "Sword Art Online",
    category: "Anime",
    director: "Tomohiko Itō",
    duration: "23 min per episode",
    year_of_publishing: 2012,
    rating: 4,
    tags: ["Action", "Adventure", "Romance"],
    product_id: "007",
    price: 27.99,
    image: "https://i.ibb.co.com/wRWjs0w/product14-copyright-600x700.jpg",
    description:
      "Thousands of players are trapped in a new virtual MMORPG, and their only way out is to clear the game.",
  },
  {
    name: "Jujutsu Kaisen",
    category: "Anime",
    director: "Sunghoo Park",
    duration: "23 min per episode",
    year_of_publishing: 2020,
    rating: 5,
    tags: ["Action", "Supernatural", "Dark Fantasy"],
    product_id: "008",
    price: 31.99,
    image: "https://i.ibb.co.com/S5bRwNs/product15-copyright-600x700.jpg",
    description:
      "Yuji Itadori joins a secret organization to protect the world from curses after becoming the host of a powerful curse.",
  },
  {
    name: "Tokyo Ghoul",
    category: "Anime",
    director: "Shuhei Morita",
    duration: "24 min per episode",
    year_of_publishing: 2014,
    rating: 4.5,
    tags: ["Action", "Supernatural", "Horror"],
    product_id: "009",
    price: 26.99,
    image: "https://i.ibb.co.com/kGfJBKx/product16-copyright-600x700.jpg",
    description:
      "An ordinary college student is turned into a half-ghoul and must learn to live in both worlds.",
  },
  {
    name: "My Hero Academia",
    category: "Anime",
    director: "Kenji Nagasaki",
    duration: "24 min per episode",
    year_of_publishing: 2016,
    rating: 5,
    tags: ["Action", "Superhero", "Fantasy"],
    product_id: "010",
    price: 32.99,
    image: "https://i.ibb.co.com/vXdQX2z/product17-copyright-600x700.jpg",
    description:
      "In a world where nearly everyone has superpowers, a powerless boy enrolls in a hero academy to become a true hero.",
  },
  {
    name: "Sword Art Online",
    category: "Anime",
    director: "Tomohiko Itō",
    duration: "23 min per episode",
    year_of_publishing: 2012,
    rating: 4,
    tags: ["Action", "Adventure", "Romance"],
    product_id: "007",
    price: 27.99,
    image: "https://i.ibb.co.com/S5bRwNs/product15-copyright-600x700.jpgg",
    description:
      "Thousands of players are trapped in a new virtual MMORPG, and their only way out is to clear the game.",
  },
  {
    name: "Jujutsu Kaisen",
    category: "Anime",
    director: "Sunghoo Park",
    duration: "23 min per episode",
    year_of_publishing: 2020,
    rating: 5,
    tags: ["Action", "Supernatural", "Dark Fantasy"],
    product_id: "008",
    price: 31.99,
    image: "https://i.ibb.co.com/VC7Pn6w/product12-copyright-600x700.jpg",
    description:
      "Yuji Itadori joins a secret organization to protect the world from curses after becoming the host of a powerful curse.",
  },
  {
    name: "Tokyo Ghoul",
    category: "Anime",
    director: "Shuhei Morita",
    duration: "24 min per episode",
    year_of_publishing: 2014,
    rating: 4.5,
    tags: ["Action", "Supernatural", "Horror"],
    product_id: "009",
    price: 26.99,
    image: "https://i.ibb.co.com/jHXP4W4/product13-copyright-600x700.jpg",
    description:
      "An ordinary college student is turned into a half-ghoul and must learn to live in both worlds.",
  },
  {
    name: "My Hero Academia",
    category: "Anime",
    director: "Kenji Nagasaki",
    duration: "24 min per episode",
    year_of_publishing: 2016,
    rating: 5,
    tags: ["Action", "Superhero", "Fantasy"],
    product_id: "010",
    price: 32.99,
    image: "https://i.ibb.co.com/kGfJBKx/product16-copyright-600x700.jpg",
    description:
      "In a world where nearly everyone has superpowers, a powerless boy enrolls in a hero academy to become a true hero.",
  },
  {
    name: "Dragon Ball Z",
    category: "Anime",
    director: "Daisuke Nishio",
    duration: "24 min per episode",
    year_of_publishing: 1989,
    rating: 4.5,
    tags: ["Action", "Martial Arts", "Adventure"],
    product_id: "011",
    price: 28.99,
    image: "https://i.ibb.co.com/vXdQX2z/product17-copyright-600x700.jpg",
    description:
      "Goku and his friends defend the Earth from powerful foes while training to become the strongest fighters in the universe.",
  },
  {
    name: "Fairy Tail",
    category: "Anime",
    director: "Shinji Ishihira",
    duration: "24 min per episode",
    year_of_publishing: 2009,
    rating: 4,
    tags: ["Action", "Adventure", "Fantasy"],
    product_id: "012",
    price: 25.99,
    image: "https://i.ibb.co.com/jHXP4W4/product13-copyright-600x700.jpg",
    description:
      "Lucy Heartfilia joins the wizard guild Fairy Tail and embarks on magical adventures with her guildmates.",
  },
  {
    name: "Neon Genesis Evangelion",
    category: "Anime",
    director: "Hideaki Anno",
    duration: "24 min per episode",
    year_of_publishing: 1995,
    rating: 5,
    tags: ["Mecha", "Psychological", "Sci-Fi"],
    product_id: "013",
    price: 29.99,
    image: "https://i.ibb.co.com/kGfJBKx/product16-copyright-600x700.jpg",
    description:
      "A group of teenagers pilot giant mechs to defend Earth from mysterious beings known as Angels.",
  },
  {
    name: "Spirited Away",
    category: "Anime",
    director: "Hayao Miyazaki",
    duration: "125 min",
    year_of_publishing: 2001,
    rating: 5,
    tags: ["Adventure", "Fantasy", "Drama"],
    product_id: "014",
    price: 19.99,
    image: "https://i.ibb.co.com/kGfJBKx/product16-copyright-600x700.jpg",
    description:
      "A young girl becomes trapped in a magical world and must find a way to free herself and her parents.",
  },
];
