export const shop = [
  {
    title: "Naruto",
    category: "Manga",
    author: "Masashi Kishimoto",
    pages: 192,
    yearPublished: 1999,
    rating: 4.9,
    genres: ["Action", "Adventure", "Fantasy"],
    price: 29.99,
    imageUrl: "https://i.ibb.co.com/zHKWQ6r/Naruto.jpg",
    description:
      "In the Hidden Leaf Village, a young ninja named Naruto Uzumaki struggles with loneliness and the burden of being an outcast. As he trains rigorously to become the next Hokage, he faces formidable foes, uncovers secrets of his past, and forges unbreakable bonds with friends like Sakura and Sasuke. This coming-of-age story is rich with action, heartfelt moments, and themes of perseverance, friendship, and the importance of never giving up on one’s dreams. Experience the epic battles, emotional turmoil, and the journey of a boy who seeks recognition and strives to protect those he loves.",
    ISBN: "978-1421502403",
    language: "English",
    publisher: "VIZ Media",
    totalSold: 120,
  },
  {
    title: "One Piece",
    category: "Manga",
    author: "Eiichiro Oda",
    pages: 216,
    yearPublished: 1997,
    rating: 4.8,
    genres: ["Action", "Adventure", "Fantasy"],
    price: 32.99,
    imageUrl: "https://i.ibb.co.com/bgFN41R/OnePiece.jpg",
    description:
      "Join Monkey D. Luffy, a cheerful and determined young pirate with the unique ability to stretch his body like rubber after eating a mysterious fruit. Luffy embarks on a grand adventure across the treacherous Grand Line in search of the legendary treasure known as One Piece, which will make him the Pirate King. Alongside his diverse and loyal crew, the Straw Hat Pirates, Luffy faces powerful adversaries, unravels the mysteries of the world, and discovers the true meaning of friendship and freedom. One Piece is a timeless tale filled with thrilling adventures, captivating characters, and an intricate world full of surprises.",

    ISBN: "978-1421515120",
    language: "English",
    publisher: "VIZ Media",
    totalSold: 95,
  },
  {
    title: "Fullmetal Alchemist",
    category: "Manga",
    author: "Hiromu Arakawa",
    pages: 180,
    yearPublished: 2001,
    rating: 5.0,
    genres: ["Action", "Adventure", "Fantasy"],
    price: 34.99,
    imageUrl: "https://i.ibb.co.com/sm4QGF4/FULLMETAL.jpg",
    description:
      "Fullmetal Alchemist follows the story of Edward and Alphonse Elric, two brothers who delve into the world of alchemy in a desperate quest to reclaim what they've lost. After a failed attempt to bring their mother back to life using forbidden alchemical techniques, Edward loses his left leg and Alphonse his entire body. In a bid to restore their physical forms, Edward seeks the legendary Philosopher's Stone, a powerful artifact that amplifies an alchemist's abilities.As they navigate the perilous landscape of a war-torn nation, the brothers confront formidable foes and uncover dark secrets that challenge their beliefs and values. Joined by a diverse group of allies, they explore profound themes of sacrifice, morality, and the bonds of brotherhood. Fullmetal Alchemist is an epic tale of adventure and redemption that intertwines action, emotion, and philosophical depth within its richly crafted universe.",
    ISBN: "978-1421508393",
    language: "English",
    publisher: "Square Enix",
    totalSold: 85,
  },
  {
    title: "Attack on Titan",
    category: "Manga",
    author: "Hajime Isayama",
    pages: 200,
    yearPublished: 2009,
    rating: 4.7,
    genres: ["Action", "Drama", "Fantasy"],
    price: 35.99,
    imageUrl: "https://i.ibb.co.com/93Dw4p3/Attack-On-Titan.jpg",
    description:
      "In a world besieged by gigantic humanoid creatures known as Titans, humanity clings to survival behind towering walls. The story centers on Eren Yeager, a passionate and headstrong youth who joins the military to eradicate the Titans after witnessing the brutal murder of his mother. Alongside his friends Mikasa and Armin, Eren uncovers shocking truths about the Titans and the world beyond the walls. Attack on Titan delivers intense action, moral dilemmas, and themes of freedom, sacrifice, and the struggle against oppression, offering a dark and thrilling exploration of human resilience and the fight for survival.",

    ISBN: "978-1612620244",
    language: "English",
    publisher: "Kodansha Comics",
    totalSold: 100,
  },
  {
    title: "Death Note",
    category: "Manga",
    author: "Tsugumi Ohba & Takeshi Obata",
    pages: 195,
    yearPublished: 2003,
    rating: 4.9,
    genres: ["Psychological", "Thriller", "Mystery"],
    price: 33.99,
    imageUrl: "https://i.ibb.co.com/M8CZxLG/Death-Note.jpg",
    description:
      "Death Note follows the story of Light Yagami, a highly intelligent high school student who discovers a mysterious notebook that grants him the power to kill anyone whose name he writes in it. With a newfound sense of justice, Light embarks on a mission to eliminate criminals and create a utopia free of evil, adopting the alias 'Kira.' However, his actions attract the attention of a brilliant detective known only as 'L,' leading to a high-stakes game of cat and mouse. This gripping psychological thriller explores themes of morality, justice, and the thin line between right and wrong, captivating readers with its intricate plot and moral complexity.",

    ISBN: "978-1421501684",
    language: "English",
    publisher: "VIZ Media",
    totalSold: 110,
  },
  {
    title: "Dragon Ball",
    category: "Manga",
    author: "Akira Toriyama",
    pages: 180,
    yearPublished: 1984,
    rating: 4.8,
    genres: ["Action", "Adventure", "Fantasy"],
    price: 29.99,
    imageUrl: "https://i.ibb.co.com/RQ7TPBY/Dragon-Ball.jpgg",
    description:
      "Embark on an adventure with Goku, a young boy with extraordinary strength, as he sets out to find the Dragon Balls—seven magical orbs that summon a dragon capable of granting wishes. Along the way, Goku meets friends like Bulma, Krillin, and Master Roshi, faces off against formidable foes, and competes in epic martial arts tournaments. Dragon Ball is a legendary tale of friendship, determination, and the spirit of adventure, characterized by unforgettable battles, humorous moments, and the exploration of Goku's growth as a martial artist and hero.",

    ISBN: "978-1569319208",
    language: "English",
    publisher: "Shueisha",
    totalSold: 150,
  },
  {
    title: "My Hero Academia",
    category: "Manga",
    author: "Kohei Horikoshi",
    pages: 208,
    yearPublished: 2014,
    rating: 4.7,
    genres: ["Action", "Adventure", "Superhero"],
    price: 36.99,
    imageUrl: "https://i.ibb.co.com/dP64ddH/MyHero.jpg",
    description:
      "In a world where the majority of people possess superpowers known as Quirks, Izuku Midoriya, a Quirkless boy, dreams of becoming a hero like his idol All Might. Despite being born without powers, his determination and courage lead him to an unexpected encounter with All Might, who grants him the chance to inherit his power. As Midoriya enrolls in U.A. High School, a prestigious academy for aspiring heroes, he faces intense challenges, friendships, and rivalries that shape his journey. My Hero Academia celebrates themes of heroism, perseverance, and the importance of believing in oneself amidst overwhelming odds.",
    ISBN: "978-1421582690",
    language: "English",
    publisher: "VIZ Media",
    totalSold: 120,
  },
  {
    title: "Demon Slayer: Kimetsu no Yaiba",
    category: "Manga",
    author: "Koyoharu Gotouge",
    pages: 196,
    yearPublished: 2016,
    rating: 4.8,
    genres: ["Action", "Adventure", "Dark Fantasy"],
    price: 34.99,
    imageUrl: "https://i.ibb.co.com/HV34rVx/Deman-Slayer.jpg",
    description:
      "Demon Slayer follows Tanjiro Kamado, a kind-hearted boy who becomes a demon slayer after his family is slaughtered by demons and his younger sister Nezuko is transformed into one. Driven by the desire to avenge his family and find a cure for his sister, Tanjiro trains rigorously and faces countless demons, each with unique abilities and tragic backstories. The series explores themes of family, perseverance, and the battle between good and evil, beautifully illustrated with stunning art and heart-wrenching moments. Experience a tale of courage, hope, and the unbreakable bonds of family in this epic dark fantasy.",

    ISBN: "978-1974700523",
    language: "English",
    publisher: "Shueisha",
    totalSold: 85,
  },
  {
    title: "JoJo's Bizarre Adventure",
    category: "Manga",
    author: "Hirohiko Araki",
    pages: 256,
    yearPublished: 1987,
    rating: 4.8,
    genres: ["Adventure", "Fantasy", "Supernatural"],
    price: 39.99,
    imageUrl: "https://i.ibb.co.com/0sjTjnz/Jojo.jpg",
    description:
      "JoJo's Bizarre Adventure is an epic saga that chronicles the extraordinary lineage of the Joestar family as they battle a variety of supernatural foes throughout different generations. Starting with Jonathan Joestar in the late 19th century, each part of the series introduces a new protagonist, from the charismatic Joseph Joestar to the enigmatic Jotaro Kujo, each connected by blood and destiny.The series masterfully blends adventure, fantasy, and supernatural elements, showcasing unique abilities known as Stands—manifestations of a person's fighting spirit that grant them incredible powers. As the characters navigate perilous encounters with formidable adversaries, they confront themes of friendship, betrayal, and the struggle between good and evil.With its signature art style, memorable characters, and inventive storytelling, JoJos Bizarre Adventure has become a cultural phenomenon, offering readers a wild ride filled with humor, drama, and breathtaking battles that transcend time and space.",
    ISBN: "978-1421578808",
    language: "English",
    publisher: "Shueisha",
    totalSold: 90,
  },
  {
    title: "Bleach",
    category: "Manga",
    author: "Tite Kubo",
    pages: 192,
    yearPublished: 2001,
    rating: 4.7,
    genres: ["Action", "Adventure", "Supernatural"],
    price: 32.99,
    imageUrl: "https://i.ibb.co.com/3k5mdQL/Bleach.jpg",
    description:
      "In Bleach, the story follows Ichigo Kurosaki, a seemingly ordinary high school student who unexpectedly gains the powers of a Soul Reaper, a celestial warrior tasked with defending the living world from malevolent spirits known as Hollows. As Ichigo grapples with his newfound abilities, he is thrust into a complex realm of spiritual warfare and supernatural conflicts that challenge his understanding of life, death, and the balance between the two.Throughout his journey, Ichigo encounters a diverse cast of characters, including fellow Soul Reapers, powerful allies, and formidable foes, each with their own unique abilities and motivations. As he trains and grows stronger, Ichigo learns the importance of friendship, loyalty, and sacrifice while confronting the dark forces that threaten both the human world and the Soul Society.With its dynamic action scenes, intricate plotlines, and deep character development, Bleach has captivated fans around the globe, making it a beloved staple in the shonen manga genre. The series explores themes of duty, redemption, and the eternal struggle against evil, all set against a backdrop of striking artwork and compelling storytelling.",
    ISBN: "978-1591164418",
    language: "English",
    publisher: "Shueisha",
    totalSold: 130,
  },
  {
    title: "Berserk",
    category: "Manga",
    author: "Kentaro Miura",
    pages: 400,
    yearPublished: 1989,
    rating: 4.9,
    genres: ["Dark Fantasy", "Action", "Horror"],
    price: 49.99,
    imageUrl: "https://i.ibb.co.com/fNfV2zH/Berserk.jpg",
    description:
      "In 'Berserk,' we delve into the dark and tumultuous world of Guts, a lone mercenary marked by a tragic past and relentless determination. Set in a brutal medieval landscape, the story follows Guts as he wields his massive sword, the Dragon Slayer, and battles against an array of monstrous demons and ruthless warlords. His journey is one of vengeance and survival, shaped by the scars of betrayal and the haunting memories of his former comrades. As Guts navigates through a world rife with corruption, betrayal, and supernatural horrors, he grapples with his inner demons and the complex nature of his existence. Along the way, he encounters a diverse cast of characters, including the enigmatic Griffith, who embodies both ambition and charisma, and Casca, a fierce warrior with whom Guts forms a deep, tumultuous bond. 'Berserk' is renowned for its intricate artwork, visceral action sequences, and profound philosophical themes, exploring concepts of fate, free will, and the struggle between light and darkness. Kentaro Miura's masterful storytelling and attention to detail draw readers into an epic tale of sacrifice, ambition, and the relentless pursuit of one’s destiny. This dark fantasy series challenges the boundaries of its genre, leaving an indelible mark on manga and storytelling as a whole.",
    ISBN: "978-1593070205",
    language: "English",
    publisher: "Dark Horse",
    totalSold: 70,
  },

  {
    title: "Tokyo Ghoul",
    category: "Manga",
    author: "Sui Ishida",
    pages: 224,
    yearPublished: 2011,
    rating: 4.8,
    genres: ["Horror", "Dark Fantasy", "Supernatural"],
    price: 29.99,
    imageUrl: "https://i.ibb.co.com/J5fnpjk/Tokyo.jpg",
    description:
      "In 'Tokyo Ghoul,' we follow the harrowing journey of Ken Kaneki, a seemingly ordinary college student who becomes embroiled in a terrifying world of flesh-eating ghouls after a chance encounter with one. Following a horrific accident, Kaneki is transformed into a half-ghoul, a being caught between the human and ghoul worlds, forced to grapple with his new identity and the insatiable hunger for human flesh that comes with it. As he navigates the complexities of his dual existence, Kaneki must confront the horrors of the ghoul society, which is plagued by violence, survival instincts, and the constant threat of human hunters known as the CCG. Throughout his journey, he encounters a cast of diverse and intricate characters, each with their own motives, fears, and struggles, including the enigmatic and fierce Touka Kirishima, who introduces him to the ghoul community and helps him understand the brutal reality of his new life. 'Tokyo Ghoul' masterfully delves into themes of identity, humanity, and the moral dilemmas faced by those who exist in the shadows of society. Sui Ishida's poignant storytelling and striking artwork immerse readers in a dark, atmospheric narrative that challenges the boundaries of horror and fantasy, exploring what it truly means to be human in a world where survival often comes at a terrible cost.",
    ISBN: "978-1421580368",
    language: "English",
    publisher: "VIZ Media",
    totalSold: 85,
  },
  {
    title: "Vinland Saga",
    category: "Manga",
    author: "Makoto Yukimura",
    pages: 480,
    yearPublished: 2005,
    rating: 4.7,
    genres: ["Historical", "Adventure", "Action"],
    price: 49.99,
    imageUrl: "https://i.ibb.co.com/qMc0mLN/Saga.jpg",
    description:
      "In 'Vinland Saga,' we are immersed in the gripping tale of Thorfinn, the son of a renowned Viking warrior, who embarks on a relentless quest for revenge against the man who killed his father. Set against the backdrop of medieval Scandinavia, the story intricately weaves themes of honor, brutality, and the harsh realities of Viking life. As Thorfinn grows from a naive boy into a fierce warrior, he grapples with his desire for vengeance while navigating the complexities of war and survival. The narrative spans numerous conflicts, from brutal battles to political intrigue, as Thorfinn encounters a rich tapestry of characters, including formidable foes and unexpected allies. Makoto Yukimura's masterful storytelling and breathtaking artwork bring to life the epic scope of this saga, exploring the consequences of violence and the quest for personal identity amid the chaos of conquest. Ultimately, 'Vinland Saga' delves into the profound questions of redemption and what it means to live a meaningful life in a world marked by bloodshed and ambition, offering readers an unforgettable journey through history.",
    ISBN: "978-1612624204",
    language: "English",
    publisher: "Kodansha Comics",
    totalSold: 95,
  },
  {
    title: "Akira",
    category: "Manga",
    author: "Katsuhiro Otomo",
    pages: 350,
    yearPublished: 1982,
    rating: 4.9,
    genres: ["Sci-Fi", "Dystopian", "Cyberpunk"],
    price: 59.99,
    imageUrl: "https://i.ibb.co.com/HCc9tKk/AKIRA.jpg",
    description:
      "Set in a post-apocalyptic Tokyo, 'Akira' follows the turbulent journey of Kaneda, a rebellious biker, and his friend Tetsuo, who develops extraordinary psychic powers after a motorcycle accident. As Tetsuo's abilities spiral out of control, he becomes the target of a secret government project that aims to control his powers and prevent the rise of a new threat known as Akira, a child with god-like abilities. The narrative delves deep into themes of friendship, power, and the consequences of technological advancement. As Kaneda races against time to save his friend from a fate that could bring destruction to Neo-Tokyo, readers are immersed in a visually stunning world filled with political intrigue, dystopian struggles, and the fight for survival. Katsuhiro Otomo's groundbreaking work not only redefined the sci-fi genre in manga but also became a cultural phenomenon, exploring the darker sides of human ambition and the essence of what it means to wield immense power.",
    ISBN: "978-1935429005",
    language: "Japanese",
    publisher: "Kodansha Comics",
    totalSold: 65,
  },
  {
    title: "Black Clover",
    category: "Manga",
    author: "Yūki Tabata",
    pages: 192,
    yearPublished: 2015,
    rating: 4.6,
    genres: ["Action", "Adventure", "Fantasy"],
    price: 29.99,
    imageUrl: "https://i.ibb.co.com/gWzY64z/Black-Clover.jpg",
    description:
      "In a world where magic is everything, 'Black Clover' tells the story of Asta, a determined boy born without any magical abilities in a society that values them above all. Despite this apparent disadvantage, Asta dreams of becoming the Wizard King, the highest honor achievable in the Clover Kingdom. Alongside his childhood rival and best friend, Yuno, who is exceptionally gifted with magic, Asta embarks on a quest filled with thrilling battles, magical creatures, and powerful foes. As he joins the Black Bulls, a group of misfit magic knights, Asta discovers the true meaning of strength, teamwork, and perseverance. The series masterfully blends action, humor, and friendship, showcasing Asta's relentless spirit and the bonds he forms with his comrades as they face formidable challenges and work towards their shared dream. Yūki Tabata's vibrant artwork and compelling storytelling capture the heart of this adventurous tale, inspiring readers to believe in themselves and the power of hard work.",
    ISBN: "978-1421587190",
    language: "English",
    publisher: "Shueisha",
    totalSold: 110,
  },
  {
    title: "Chainsaw Man",
    category: "Manga",
    author: "Tatsuki Fujimoto",
    pages: 192,
    yearPublished: 2018,
    rating: 4.7,
    genres: ["Action", "Horror", "Fantasy"],
    price: 32.99,
    imageUrl: "https://i.ibb.co.com/SQ8mmG1/Chainsaw-man.jpg",
    description:
      "In a dark and chaotic world, Denji is a young man burdened by debt and desperation. Armed with the ability to transform parts of his body into chainsaws, he battles ferocious devils and demons that threaten humanity. As he fights to survive and fulfill his dreams, Denji discovers the harsh realities of his existence, the complexities of human emotions, and the bonds of friendship that can either save or doom him. This thrilling journey blends action, horror, and fantasy, immersing readers in a gripping tale of survival against overwhelming odds.",

    ISBN: "978-1974709939",
    language: "English",
    publisher: "Shueisha",
    totalSold: 120,
  },
  {
    title: "Blue Exorcist",
    category: "Manga",
    author: "Kazue Kato",
    pages: 202,
    yearPublished: 2009,
    rating: 4.5,
    genres: ["Action", "Fantasy", "Supernatural"],
    price: 31.99,
    imageUrl: "https://i.ibb.co.com/CJr6pFy/Blue.jpg",
    description:
      "Rin Okumura’s life takes a dramatic turn when he discovers that he is the son of Satan himself. Struggling with his demonic heritage, Rin decides to defy his destiny by becoming an exorcist to protect humanity from the dark forces that threaten it. Alongside his brother and fellow exorcists at the prestigious True Cross Academy, Rin embarks on a journey filled with supernatural battles, self-discovery, and moral dilemmas. As he grapples with his powers and questions of identity, he must decide if he can truly escape his fate or if darkness is an unavoidable part of his path.",
    ISBN: "978-1421540324",
    language: "English",
    publisher: "Shueisha",
    totalSold: 90,
  },
  {
    title: "Hunter x Hunter",
    category: "Manga",
    author: "Yoshihiro Togashi",
    pages: 210,
    yearPublished: 1998,
    rating: 4.8,
    genres: ["Action", "Adventure", "Fantasy"],
    price: 33.99,
    imageUrl: "https://i.ibb.co.com/cT09ZNQ/Hunter.jpg",
    description:
      "Gon Freecss, a spirited young boy with boundless curiosity and determination, embarks on an epic journey to become a legendary Hunter in hopes of finding his missing father, who left him years ago to pursue the same path. As he faces rigorous trials, dangerous foes, and supernatural challenges, Gon meets friends who become invaluable allies, each with their own dreams and skills. Together, they navigate the perilous Hunter world, uncovering secrets and pushing their limits in battles of both strength and wit. Gon’s quest becomes more than just a search for his father; it’s a journey of self-discovery and the adventure of a lifetime.",
    ISBN: "978-1421506481",
    language: "English",
    publisher: "VIZ Media",
    totalSold: 115,
  },
  {
    title: "Mob Psycho 100",
    category: "Manga",
    author: "ONE",
    pages: 192,
    yearPublished: 2012,
    rating: 4.6,
    genres: ["Action", "Comedy", "Supernatural"],
    price: 30.99,
    imageUrl: "https://i.ibb.co.com/4WJXdvM/100.jpg",
    description:
      "Shigeo Kageyama, known as Mob, appears to be an average, unremarkable middle schooler, but he possesses extraordinary psychic abilities that make him one of the most powerful psychics alive. Despite his immense power, Mob desires nothing more than a normal life, free from supernatural conflicts. However, as he navigates the trials of adolescence and battles inner struggles, Mob faces challenges that push him to confront both his powers and his emotions. With each surge of psychic energy, Mob inches closer to a dangerous limit, where his hidden power could spiral out of control. Can he find balance between his abilities and his desire for a normal life?",
    ISBN: "978-1974700554",
    language: "English",
    publisher: "Shogakukan",
    totalSold: 80,
  },
  {
    title: "Yona of the Dawn",
    category: "Manga",
    author: "Mizuho Kusanagi",
    pages: 192,
    yearPublished: 2009,
    rating: 4.7,
    genres: ["Fantasy", "Adventure", "Romance"],
    price: 29.99,
    imageUrl: "https://i.ibb.co.com/XYskmY7/Yona.jpg",
    description:
      "Princess Yona lives a life of luxury and privilege in the Kingdom of Kouka, sheltered from the harsh realities of her world. However, her peaceful life shatters when betrayal forces her to flee her home. With her childhood friend and bodyguard Hak at her side, Yona embarks on a perilous journey to survive and reclaim her throne. Along the way, she learns of her kingdom’s suffering and gathers loyal allies, including the legendary Dragon Warriors. As Yona transforms from a naive princess into a fierce and compassionate leader, she faces trials that challenge her courage, heart, and resolve.",
    ISBN: "978-1421587817",
    language: "Japanese",
    publisher: "Shueisha",
    totalSold: 70,
  },
  {
    title: "Neon Genesis Evangelion",
    category: "Manga",
    author: "Yoshiyuki Sadamoto",
    pages: 194,
    yearPublished: 1994,
    rating: 4.8,
    genres: ["Sci-Fi", "Drama", "Mecha"],
    price: 35.99,
    imageUrl: "https://i.ibb.co.com/nc93ZsX/Evangion.jpg",
    description:
      "In a post-apocalyptic world, humanity's fate hangs in the balance as mysterious beings known as 'Angels' threaten to destroy the remaining civilization. To combat this existential threat, a select group of teenagers, including the reluctant protagonist Shinji Ikari, are recruited to pilot bio-mechanical units called 'Evangelions.' These powerful yet enigmatic machines are humanity’s last line of defense. As they battle the Angels, Shinji and his fellow pilots face intense psychological struggles, discovering truths about themselves, their connections to each other, and the dark secrets underlying the Evangelion project.",

    ISBN: "978-1569313077",
    language: "Japanese",
    publisher: "Kadokawa Shoten",
    totalSold: 60,
  },
  {
    title: "Fairy Tail",
    category: "Manga",
    author: "Hiro Mashima",
    pages: 208,
    yearPublished: 2006,
    rating: 4.6,
    genres: ["Action", "Adventure", "Fantasy"],
    price: 29.99,
    imageUrl: "https://i.ibb.co.com/SRkzg4R/Fairy-Tail.jpg",
    description:
      "In the kingdom of Fiore, young celestial wizard Lucy Heartfilia dreams of joining Fairy Tail, the world-renowned guild of powerful and loyal mages. Her life changes forever when she encounters Natsu Dragneel, a dragon slayer wizard searching for his missing dragon foster parent. Together with their guildmates, they embark on exhilarating adventures, battling dark forces, uncovering ancient secrets, and forming unbreakable bonds of friendship. As they face formidable foes and overcome personal struggles, Lucy, Natsu, and the members of Fairy Tail prove the strength of their guild and the power of family.",
    ISBN: "978-1612622767",
    language: "English",
    publisher: "Kodansha Comics",
    totalSold: 100,
  },
  {
    title: "The Promised Neverland",
    category: "Manga",
    author: "Kaiu Shirai & Posuka Demizu",
    pages: 192,
    yearPublished: 2016,
    rating: 4.7,
    genres: ["Horror", "Thriller", "Fantasy"],
    price: 31.99,
    imageUrl: "https://i.ibb.co.com/b6Lsm3C/The-Promised.jpg",
    description:
      "Set in the seemingly idyllic Grace Field House, young orphans Emma, Norman, and Ray live peacefully under the care of their loving 'Mom,' Isabella. However, their world shatters when they uncover the horrifying truth about the true purpose of the orphanage. Together, the trio devises a complex plan to escape, leading them on a suspenseful journey of survival, strategy, and friendship. Facing a ruthless enemy, they must outsmart those who wish to trap them, venturing into a dangerous world that lies beyond the orphanage walls.",
    ISBN: "978-1421597120",
    language: "English",
    publisher: "Shueisha",
    totalSold: 85,
  },
  {
    title: "Soul Eater",
    category: "Manga",
    author: "Atsushi Ōkubo",
    pages: 186,
    yearPublished: 2004,
    rating: 4.6,
    genres: ["Action", "Adventure", "Supernatural"],
    price: 32.99,
    imageUrl: "https://i.ibb.co.com/9sHCL8m/Soul.jpg",
    description:
      "In the vibrant, mysterious world of Death City, students of the Death Weapon Meister Academy are trained to become powerful warriors, wielding sentient weapons to protect humanity from malevolent souls. Under the guidance of the enigmatic Shinigami, young Meisters and their weapon partners face dangerous missions, forming unbreakable bonds and honing their skills. Soul Eater follows the journeys of Maka Albarn and her weapon partner, Soul, along with their friends, as they battle witches, demons, and twisted souls in a quest to create the ultimate Death Scythe. Through teamwork, resilience, and courage, they strive to uphold peace in a world on the brink of chaos.",
    ISBN: "978-0316073578",
    language: "English",
    publisher: "Square Enix",
    totalSold: 110,
  },
  {
    title: "Sword Art Online",
    category: "Manga",
    author: "Reki Kawahara",
    pages: 200,
    yearPublished: 2010,
    rating: 4.5,
    genres: ["Sci-Fi", "Adventure", "Fantasy"],
    price: 34.99,
    imageUrl: "https://i.ibb.co.com/25nDFnF/Sword-Art-Online.jpg",
    description:
      "In a near-future world, players are immersed in a groundbreaking virtual reality MMORPG called Sword Art Online. However, the excitement quickly turns to terror when they discover that they are trapped inside the game, with no way to log out. If they die in the game, they die in real life. As players band together, the protagonist, Kirito, must navigate a treacherous world filled with formidable enemies and intricate quests. With time running out and the stakes higher than ever, Kirito fights not only to survive but to find a way to free all trapped players. Sword Art Online explores the themes of friendship, courage, and the consequences of technology, all while delivering breathtaking action and adventure.",
    ISBN: "978-0316371247",
    language: "Japanese",
    publisher: "Yen Press",
    totalSold: 75,
  },
  {
    title: "D.Gray-man",
    category: "Manga",
    author: "Katsura Hoshino",
    pages: 210,
    yearPublished: 2004,
    rating: 4.7,
    genres: ["Action", "Adventure", "Fantasy"],
    price: 29.99,
    imageUrl: "https://i.ibb.co.com/wQq69Sc/D-Gray-Man.jpg",
    description:
      "In a world plagued by darkness, young exorcist Allen Walker embarks on a perilous journey to combat demonic forces known as Akuma. With a cursed past and a unique power to purify these soulless machines, Allen joins the Black Order, an organization dedicated to protecting humanity from the threats posed by the Millennium Earl and his minions. As he battles formidable foes and uncovers the secrets of his own origins, Allen must navigate the complexities of friendship, loyalty, and sacrifice. D.Gray-man is a gripping tale of adventure and bravery, set against a backdrop of supernatural battles and deep emotional struggles.",

    ISBN: "978-1421510518",
    language: "English",
    publisher: "Shueisha",
    totalSold: 95,
  },
  {
    title: "Noragami",
    category: "Manga",
    author: "Adachitoka",
    pages: 180,
    yearPublished: 2010,
    rating: 4.7,
    genres: ["Fantasy", "Adventure", "Supernatural"],
    price: 30.99,
    imageUrl: "https://i.ibb.co.com/z5yVh0s/Noragami.jpg",
    description:
      "In the bustling streets of modern Japan, Yato is a minor god with dreams of grandeur, but he lacks followers and the means to achieve his goals. Determined to earn recognition and build his own shrine, Yato takes on odd jobs for just five yen, facing spirits and supernatural beings along the way. His journey becomes intertwined with Hiyori, a girl who saves him and unexpectedly becomes involved in his world of gods and phantoms. As they navigate the challenges of both the human and spirit realms, Yato confronts his past, battles powerful enemies, and discovers what it truly means to be a god. Noragami is an exhilarating blend of action, humor, and heartfelt moments that explores themes of identity, friendship, and redemption.",
    ISBN: "978-1612629070",
    language: "English",
    publisher: "Kodansha Comics",
    totalSold: 100,
  },
  {
    title: "Magi: The Labyrinth of Magic",
    category: "Manga",
    author: "Shinobu Ohtaka",
    pages: 192,
    yearPublished: 2009,
    rating: 4.6,
    genres: ["Adventure", "Fantasy", "Magic"],
    price: 33.99,
    imageUrl: "https://i.ibb.co.com/x83T0Fp/Magi.jpg",
    description:
      "In a vibrant world inspired by the tales of the Arabian Nights, a young boy named Aladdin embarks on an extraordinary journey filled with adventure, magic, and discovery. Guided by his mystical flute, which summons a powerful djinn named Ugo, Aladdin explores ancient dungeons, battles fierce enemies, and forms unbreakable bonds with friends such as Alibaba and Morgiana. Together, they navigate a landscape rich with political intrigue, legendary treasures, and the hidden secrets of their own destinies. 'Magi: The Labyrinth of Magic' combines captivating storytelling with stunning artwork, immersing readers in a fantastical world where courage and friendship reign supreme.",
    ISBN: "978-1421559517",
    language: "Japanese",
    publisher: "Shueisha",
    totalSold: 85,
  },
  {
    title: "Black Butler",
    category: "Manga",
    author: "Yana Toboso",
    pages: 180,
    yearPublished: 2006,
    rating: 4.8,
    genres: ["Mystery", "Fantasy", "Historical"],
    price: 30.99,
    imageUrl: "https://i.ibb.co.com/72Psj27/Black-Butler.jpg",
    description:
      "Set against the darkly enchanting backdrop of Victorian England, 'Black Butler' follows the life of Ciel Phantomhive, a young nobleman with a mysterious past and a reputation as the Queen's Watchdog. After a tragic event leads to the death of his parents, Ciel makes a pact with Sebastian, a demon butler who possesses extraordinary abilities. Together, they investigate a series of mysterious crimes and uncover hidden truths within the aristocracy. As they delve deeper into the shadows of society, Ciel grapples with his thirst for vengeance while navigating the complexities of loyalty and power. This gripping tale blends elements of mystery, fantasy, and dark humor, creating a unique narrative that captivates readers.",
    ISBN: "978-0316080842",
    language: "English",
    publisher: "Square Enix",
    totalSold: 90,
  },
  {
    title: "Claymore",
    category: "Manga",
    author: "Norihiro Yagi",
    pages: 190,
    yearPublished: 2001,
    rating: 4.7,
    genres: ["Dark Fantasy", "Action", "Supernatural"],
    price: 32.99,
    imageUrl: "https://i.ibb.co.com/fHSVhJ2/Claymore.jpg",
    description:
      "In a dark and unforgiving medieval world, 'Claymore' tells the story of a group of female warriors known as Claymores, who are half-human and half-Yoma, a monstrous race that preys on humans. The tale centers around Clare, a fierce and determined Claymore, as she battles Yoma to protect humanity and avenge her past. With each fight, Clare must confront not only the monsters outside but also the darkness within herself and her fellow warriors. As she delves deeper into the secrets of the organization that created them, Clare discovers the true nature of her powers and the fate that awaits her. With intense action, complex characters, and a hauntingly beautiful art style, 'Claymore' is a captivating exploration of identity, sacrifice, and the struggle between light and darkness.",
    ISBN: "978-1421506184",
    language: "Japanese",
    publisher: "Shueisha",
    totalSold: 85,
  },
];

export const movies = [
  {
    title: "A Silent Voice",
    category: "Movie",
    director: "Naoko Yamada",
    duration: "130 minutes",
    yearPublished: 2016,
    rating: 4.8,
    genres: ["Drama", "Romance"],
    imageUrl: [
      "https://i.ibb.co.com/F3bPVXM/A-Silent-Voice.jpg",
      "https://i.ibb.co.com/8sMwVgt/A-Silent-Voice1.jpg",
      "https://i.ibb.co.com/Z2HjK3M/A-Silent-Voice2.jpg",
    ],
    description:
      "A Silent Voice is an emotional story about a boy named Shoya Ishida who bullies Shoko Nishimiya, a deaf girl, in elementary school. Shoya’s actions lead to Shoko transferring schools, and he is later ostracized and isolated by his classmates. Years later, filled with regret and seeking redemption, Shoya sets out to reconnect with Shoko and make amends. The movie explores themes of forgiveness, friendship, bullying, and the struggle for self-acceptance, presenting a deeply moving narrative of overcoming one's past mistakes and finding healing through connection.",
    language: "Japanese",
    publisher: "Kyoto Animation",
    totalViews: 3200000,
  },
  {
    title: "Dragon Ball Mystical Adventure",
    category: "Movie",
    director: "Kazuhisa Takenouchi",
    duration: "48 minutes",
    yearPublished: 1988,
    rating: 4.7,
    genres: ["Action", "Adventure", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/2W4t7gZ/Dragon-Ball-Mystical-Adventure.jpg",
      "https://i.ibb.co.com/VVd90pQ/Dragon-Ball-Mystical-Adventure1.jpg",
      "https://i.ibb.co.com/q05d1NF/Dragon-Ball-Mystical-Adventure2.jpg",
    ],
    description:
      "Dragon Ball Mystical Adventure follows Goku and Krillin as they participate in a martial arts tournament in a kingdom that is thrown into chaos by corrupt officials. Emperor Chiaotzu’s fiancée, Ran Ran, is kidnapped, and with the help of Goku and his friends, he sets out to find her. This film combines action, humor, and the unique charm of the Dragon Ball universe, highlighting Goku’s journey of growth and his encounters with various allies and foes, as well as his continued pursuit of strength and friendship.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 2500000,
  },
  {
    title: "Dragon Ball Super: Broly",
    category: "Movie",
    director: "Tatsuya Nagamine",
    duration: "100 minutes",
    yearPublished: 2018,
    rating: 4.8,
    genres: ["Action", "Adventure", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/GHdg3Cf/Dragon-Ball-Super-Broly.jpg",
      "https://i.ibb.co.com/vzs1MPv/Dragon-Ball-Super-Broly1.jpg",
      "https://i.ibb.co.com/nmNYP0h/Dragon-Ball-Super-Broly2.jpg",
    ],
    description:
      "Dragon Ball Super: Broly brings the legendary Saiyan, Broly, into the canon Dragon Ball universe as he faces off against Goku and Vegeta. This thrilling action-packed movie delves into the origins of Saiyan race, the downfall of Planet Vegeta, and the fierce rivalry between Saiyan warriors. Broly's sheer power and tragic backstory make him a complex and formidable opponent. With stunning fight scenes and dynamic animation, the film explores themes of revenge, family ties, and the limitless potential of Saiyan strength as Goku, Vegeta, and Broly push themselves beyond their limits.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 5800000,
  },
  {
    title: "Dragon Ball Super: Super Hero",
    category: "Movie",
    director: "Tetsuro Kodama",
    duration: "99 minutes",
    yearPublished: 2022,
    rating: 4.5,
    genres: ["Action", "Adventure", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/59ZWwGp/Dragon-Ball-Super-Super-Hero.jpg",
      "https://i.ibb.co.com/z7ynHPB/Dragon-Ball-Super-Super-Hero1.jpg",
      "https://i.ibb.co.com/hZYkQSF/Dragon-Ball-Super-Super-Hero2.jpg",
    ],
    description:
      "Dragon Ball Super: Super Hero follows Gohan and Piccolo as they face new threats from the Red Ribbon Army, who have created two powerful androids to exact revenge. The film takes a unique approach by shifting the spotlight to Gohan’s growth and his journey to rekindle his fighting spirit. With well-choreographed action sequences, the movie also emphasizes the importance of mentorship and family as Piccolo and Gohan team up to protect Earth. It explores the legacy of past enemies and the idea of heroism within the Dragon Ball universe, focusing on characters often overlooked in the franchise’s epic battles.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 4100000,
  },
  {
    title: "Dragon Ball Z: Battle of Gods",
    category: "Movie",
    director: "Masahiro Hosoda",
    duration: "85 minutes",
    yearPublished: 2013,
    rating: 4.6,
    genres: ["Action", "Adventure", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/kh1w31h/Dragon-Ball-Z-Battle-of-Gods.jpg",
      "https://i.ibb.co.com/wNVDDQy/Dragon-Ball-Z-Battle-of-Gods1.jpg",
    ],
    description:
      "Dragon Ball Z: Battle of Gods introduces Beerus, the God of Destruction, who awakens after years of slumber and challenges Earth’s mightiest warriors. Goku, curious and eager to test his limits, attains the Super Saiyan God form to match Beerus’s strength. This film is notable for its humor, new character dynamics, and insight into the hierarchy of deities in the Dragon Ball universe. Battle of Gods combines intense fights with lighthearted moments, as Earth’s defenders rally to protect their planet from a force unlike any they have faced before.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 4600000,
  },
  {
    title: "Dragon Ball Z Kai",
    category: "Movie",
    director: "Yasuhiro Nowatari",
    duration: "98 episodes",
    yearPublished: 2009,
    rating: 4.7,
    genres: ["Action", "Adventure", "Fantasy"],
    imageUrl: ["https://i.ibb.co.com/2W9C2Wc/Dragon-Ball-Z-Kai.jpg"],
    description:
      "Dragon Ball Z Kai is a remastered and condensed version of the original Dragon Ball Z series, removing filler episodes and enhancing the animation quality. The series covers iconic sagas such as the Saiyan Saga, Frieza Saga, Cell Saga, and Majin Buu Saga, staying truer to Akira Toriyama’s manga. With improved pacing and high-definition visuals, Dragon Ball Z Kai offers fans a fresh look at the legendary battles and character growth that define the Dragon Ball series.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 12000000,
  },
  {
    title: "Dragon Ball Z: Resurrection 'F'",
    category: "Movie",
    director: "Tadayoshi Yamamuro",
    duration: "93 minutes",
    yearPublished: 2015,
    rating: 4.5,
    genres: ["Action", "Adventure", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/WPXnp6X/Dragon-Ball-Z-Resurrection-F.jpg",
      "https://i.ibb.co.com/4thTvKm/Dragon-Ball-Z-Resurrection-F-1.jpg",
    ],
    description:
      "In Dragon Ball Z: Resurrection 'F', the villain Frieza is resurrected and seeks revenge on Goku and the Z Fighters. Frieza trains for the first time to reach a powerful new form, Golden Frieza, and attacks Earth with a massive army. Goku and Vegeta, now training under Whis, return to defend their planet in a series of epic battles. The movie showcases Frieza’s unparalleled hatred for Goku and the fierce rivalry that fuels their clash, providing thrilling combat and stunning animation as the heroes face their old enemy at his strongest.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 5200000,
  },
  {
    title: "Ghost in the Shell",
    category: "Movie",
    director: "Mamoru Oshii",
    duration: "82 minutes",
    yearPublished: 1995,
    rating: 4.8,
    genres: ["Action", "Sci-Fi", "Cyberpunk"],
    imageUrl: [
      "https://i.ibb.co.com/YX78Hjm/Ghost-in-the-Shell.jpg",
      "https://i.ibb.co.com/GWdxjSk/Ghost-in-the-Shell1.jpg",
      "https://i.ibb.co.com/255BpNb/Ghost-in-the-Shell2.jpg",
    ],
    description:
      "Ghost in the Shell is a cyberpunk thriller that follows Major Motoko Kusanagi, a cyborg security agent, as she hunts a mysterious hacker known as the Puppet Master. Set in a futuristic world where the boundaries between human and machine are blurred, the film explores themes of identity, consciousness, and existentialism. Renowned for its philosophical depth and groundbreaking animation, Ghost in the Shell is a landmark in anime, inspiring countless works with its compelling vision of a dystopian future.",
    language: "Japanese",
    publisher: "Production I.G",
    totalViews: 3300000,
  },
  {
    title: "Honoo no Chuunin Shiken! Naruto vs Konohamaru",
    category: "Movie",
    director: "Hayato Date",
    duration: "26 minutes",
    yearPublished: 2011,
    rating: 4.2,
    genres: ["Action", "Adventure"],
    imageUrl: [
      "https://i.ibb.co.com/x2pG7Pj/Honoo-no-Chuunin-Shiken-Naruto-vs-Konohamaru.jpg",
    ],
    description:
      "This OVA, Honoo no Chuunin Shiken! Naruto vs Konohamaru, focuses on Naruto’s younger friend Konohamaru as he faces the challenges of the Chunin Exams. Konohamaru idolizes Naruto and is determined to prove his worth, even if it means facing his mentor in battle. The OVA combines humor and action as Konohamaru showcases his growth as a ninja, highlighting the bond between master and disciple while offering fans a glimpse into Naruto's role as a mentor to the next generation.",
    language: "Japanese",
    publisher: "Studio Pierrot",
    totalViews: 1200000,
  },
  {
    title: "Howl's Moving Castle",
    category: "Movie",
    director: "Hayao Miyazaki",
    duration: "119 minutes",
    yearPublished: 2004,
    rating: 4.9,
    genres: ["Fantasy", "Adventure", "Romance"],
    imageUrl: [
      "https://i.ibb.co.com/KG0LfW3/Howl-s.jpg",
      "https://i.ibb.co.com/ysRDYm3/Howl-s2.jpg",
      "https://i.ibb.co.com/hmQVx6T/Howl-s3.jpg",
    ],
    description:
      "Howl’s Moving Castle is a magical tale of a young woman named Sophie, who is transformed into an old lady by a witch’s curse. Sophie’s journey leads her to the mysterious wizard Howl and his magical, walking castle, where she finds a family and begins to rediscover her inner strength. The film is a beautiful exploration of love, self-discovery, and bravery set in a fantastical world where war, magic, and enchanting landscapes come together. Hayao Miyazaki’s masterpiece is beloved for its unique characters, stunning animation, and heartfelt message about finding courage and compassion in difficult times.",
    language: "Japanese",
    publisher: "Studio Ghibli",
    totalViews: 9000000,
  },
  {
    title: "Mononoke",
    category: "Movie",
    director: "Kenji Nakamura",
    duration: "12 episodes",
    yearPublished: 2007,
    rating: 4.7,
    genres: ["Horror", "Mystery", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/PMmQwfr/Mononoke.jpg",
      "https://i.ibb.co.com/7WyfpwZ/Mononoke1.jpg",
      "https://i.ibb.co.com/4FSpFGH/Mononoke2.jpg",
    ],
    description:
      "Mononoke follows the Medicine Seller, a mysterious figure who travels through feudal Japan exorcising malevolent spirits known as Mononoke. To banish a Mononoke, he must first uncover its Form, Truth, and Reason. Each episode presents a unique supernatural case, blending horror, mystery, and surreal visuals. This series is highly acclaimed for its distinctive art style and philosophical undertones, exploring the darkness within the human heart.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 2000000,
  },
  {
    title: "Naruto Find the Crimson Four-leaf Clover",
    category: "Movie",
    director: "Hayato Date",
    duration: "17 minutes",
    yearPublished: 2003,
    rating: 4.3,
    genres: ["Action", "Adventure"],
    imageUrl: [
      "https://i.ibb.co.com/cyvq5Nz/Naruto-Find-the-Crimson-Four-leaf-Clover.jpg",
      "https://i.ibb.co.com/61H0sNb/Naruto-Find-the-Crimson-Four-leaf-Clover1.jpg",
    ],
    description:
      "This OVA follows Naruto as he sets out on a unique mission to find a rare crimson-colored four-leaf clover for a young boy in the Hidden Leaf Village. The clover is believed to grant wishes, and Naruto is determined to help the boy fulfill his heart's desire. During his journey, he encounters various challenges that test his resolve and kindness, showcasing his dedication to helping others. This short story captures Naruto's compassionate nature and his unique approach to friendship and loyalty.",
    language: "Japanese",
    publisher: "Studio Pierrot",
    totalViews: 1500000,
  },
  {
    title: "Naruto Shippûden The Movie 3: Inheritors of the Will of Fire",
    category: "Movie",
    director: "Masahiko Murata",
    duration: "95 minutes",
    yearPublished: 2009,
    rating: 4.6,
    genres: ["Action", "Adventure"],
    imageUrl: [
      "https://i.ibb.co.com/YXC0ShL/Naruto-Shipp-den-The-Movie-3-Inheritors-of-the-Will-of-Fire.jpg",
      "https://i.ibb.co.com/xjBck8b/Naruto-Shipp-den-The-Movie-3-Inheritors-of-the-Will-of-Fire1.jpg",
    ],
    description:
      "In this high-stakes Naruto Shippuden movie, a mysterious illness has put the lives of powerful ninjas at risk, pushing the world to the brink of war. Naruto is tasked with preventing the impending conflict by seeking out the source of the illness, believed to be linked to the rogue ninja Hiruko. As he ventures out to save his friends and protect the village, Naruto must draw on his determination and strength, staying true to the Will of Fire that binds all Konoha shinobi. This movie emphasizes the power of legacy and unity in overcoming formidable challenges.",
    language: "Japanese",
    publisher: "Studio Pierrot",
    totalViews: 2700000,
  },
  {
    title: "Naruto Shippuden the Movie: Blood Prison",
    category: "Movie",
    director: "Masahiko Murata",
    duration: "103 minutes",
    yearPublished: 2011,
    rating: 4.4,
    genres: ["Action", "Adventure"],
    imageUrl: [
      "https://i.ibb.co.com/cbSwB68/Naruto-Shippuden-the-Movie-Blood-Prison.jpg",
      "https://i.ibb.co.com/8dYgyJ8/Naruto-Shippuden-the-Movie-Blood-Prison1.jpg",
    ],
    description:
      "Wrongfully accused and imprisoned in Hozuki Castle, Naruto faces one of his most difficult challenges yet. Stripped of his powers and branded as a criminal, he must uncover the truth behind a dark conspiracy within the Blood Prison. As he battles ruthless inmates and prison guards, Naruto’s will and ingenuity are put to the ultimate test. Blood Prison is a gripping tale of resilience, filled with suspense and action, as Naruto fights to clear his name and protect his friends from a mysterious threat.",
    language: "Japanese",
    publisher: "Studio Pierrot",
    totalViews: 2100000,
  },
  {
    title: "Naruto The Lost Story - Mission: Protect the Waterfall Village",
    category: "Movie",
    director: "Hajime Kamegaki",
    duration: "40 minutes",
    yearPublished: 2003,
    rating: 4.2,
    genres: ["Action", "Adventure"],
    imageUrl: [
      "https://i.ibb.co.com/CsBgMVh/Naruto-The-Lost-Story-Mission-Protect-the-Waterfall-Village.jpg",
      "https://i.ibb.co.com/LNjR8dK/Naruto-The-Lost-Story-Mission-Protect-the-Waterfall-Village1.jpg",
    ],
    description:
      "Naruto and his team are sent on a mission to the Waterfall Village, where they must protect the village from a dangerous threat. This action-packed OVA delves into Naruto’s strong sense of duty and camaraderie as he fights to protect not just his own village, but also those in need beyond its borders. With epic battles and heartwarming moments, this story captures the essence of Naruto’s character as a protector and friend.",
    language: "Japanese",
    publisher: "Studio Pierrot",
    totalViews: 1200000,
  },
  {
    title: "Naruto the Movie 2: Legend of the Stone of Gelel",
    category: "Movie",
    director: "Hirotsugu Kawasaki",
    duration: "96 minutes",
    yearPublished: 2005,
    rating: 4.5,
    genres: ["Action", "Adventure"],
    imageUrl: [
      "https://i.ibb.co.com/BTYdSff/Naruto-the-Movie-2-Legend-of-the-Stone-of-Gelel.jpg",
      "https://i.ibb.co.com/V2zFcfc/Naruto-the-Movie-2-Legend-of-the-Stone-of-Gelel1.jpg",
    ],
    description:
      "Naruto, Sakura, and Shikamaru embark on a mission to retrieve the powerful Stone of Gelel, a mystical artifact with the potential to bring peace or destruction. The trio faces new enemies and moral dilemmas as they battle to protect the world from those seeking to exploit the stone's power. This movie explores themes of duty, sacrifice, and the strength found in unity, while delivering thrilling combat sequences and a compelling storyline.",
    language: "Japanese",
    publisher: "Studio Pierrot",
    totalViews: 2500000,
  },
  {
    title: "Naruto the Movie 3: Guardians of the Crescent Moon Kingdom",
    category: "Movie",
    director: "Toshiyuki Tsuru",
    duration: "95 minutes",
    yearPublished: 2006,
    rating: 4.3,
    genres: ["Action", "Adventure"],
    imageUrl: [
      "https://i.ibb.co.com/znFPYTH/Naruto-the-Movie-3-Guardians-of-the-Crescent-Moon-Kingdom.jpg",
      "https://i.ibb.co.com/mFKmBSP/Naruto-the-Movie-3-Guardians-of-the-Crescent-Moon-Kingdom1.jpg",
    ],
    description:
      "Naruto, Sakura, Lee, and Kakashi are assigned to protect Michiru, the prince of the Crescent Moon Kingdom, and his son Hikaru during their return to their homeland. Their journey takes a dangerous turn when they discover that the kingdom has been overrun by rebels. Naruto’s team must use their skills and strength to reclaim the kingdom and protect the royal family. This story focuses on Naruto’s unwavering loyalty and determination, as well as his growth as a protector.",
    language: "Japanese",
    publisher: "Studio Pierrot",
    totalViews: 2300000,
  },
  {
    title: "One Piece - Umi no heso daiboken hen",
    category: "Movie",
    director: "Konosuke Uda",
    duration: "46 minutes",
    yearPublished: 2000,
    rating: 4.3,
    genres: ["Adventure", "Action", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/myBB0hJ/One-piece-Umi-no-heso-daiboken-hen.jpg",
      "https://i.ibb.co.com/ZYkhzYF/One-piece-Umi-no-heso-daiboken-hen1.jpg",
    ],
    description:
      "In this special episode, the Straw Hat Pirates embark on an adventure to the 'navel of the sea'—a place filled with strange phenomena and mysterious treasures. Along the way, they encounter a host of enemies and obstacles, forcing them to work together and push their limits. This story showcases the bond and determination of the crew in their endless search for adventure and discovery.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 1400000,
  },
  {
    title: "One Piece 3D2Y - Overcome Ace's Death! Luffy's Vow to His Friends",
    category: "Movie",
    director: "Naoyuki Itou",
    duration: "107 minutes",
    yearPublished: 2014,
    rating: 4.8,
    genres: ["Action", "Adventure", "Drama"],
    imageUrl: [
      "https://i.ibb.co.com/8msnDQd/One-Piece-3-D2-Y-Overcome-Ace-s-Death-Luffy-s-Vow-to-His-Friends.jpg",
      "https://i.ibb.co.com/PTRWJkP/One-Piece-3-D2-Y-Overcome-Ace-s-Death-Luffy-s-Vow-to-His-Friends1.jpg",
    ],
    description:
      "Set during the two-year training period, this special episode delves into Luffy's inner turmoil and resolve after Ace's tragic death. With the help of Rayleigh and an unexpected ally, Luffy hones his skills and strength, promising to protect his crew and face any challenge that comes his way. This intense story highlights Luffy's growth, determination, and unbreakable bond with his friends.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 2900000,
  },
  {
    title: "One Piece Adventure of Nebulandia",
    category: "Movie",
    director: "Konosuke Uda",
    duration: "106 minutes",
    yearPublished: 2015,
    rating: 4.5,
    genres: ["Action", "Adventure"],
    imageUrl: [
      "https://i.ibb.co.com/80Xb8jD/One-Piece-Adventure-of-Nebulandia.jpg",
      "https://i.ibb.co.com/6BTgDxc/One-Piece-Adventure-of-Nebulandia1.jpg",
    ],
    description:
      "The Straw Hats are lured to Nebulandia, an island with anti-Devil Fruit properties, by the Foxy Pirates. Stripped of their powers and outwitted by Foxy's schemes, they must rely on their wits and teamwork to escape. This special highlights the crew's adaptability, cleverness, and unbreakable spirit in the face of overwhelming odds.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 1600000,
  },
  {
    title: "One Piece - Alabasta: The Desert Princess and the Pirates",
    category: "Movie",
    director: "Takahiro Imamura",
    duration: "90 minutes",
    yearPublished: 2007,
    rating: 4.7,
    genres: ["Action", "Adventure", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/gRnqYtQ/One-Piece-Alabasta-The-Desert-Princess-and-the-Pirates.jpg",
      "https://i.ibb.co.com/q1bfHK3/One-Piece-Alabasta-The-Desert-Princess-and-the-Pirates1.jpg",
    ],
    description:
      "The movie follows the Straw Hat Pirates as they venture to the desert kingdom of Alabasta to help Princess Vivi stop a civil war instigated by the cunning Warlord Crocodile. With intense battles, high stakes, and emotional moments, this story explores themes of loyalty, sacrifice, and the lengths friends will go to for each other.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 2500000,
  },
  {
    title: "One Piece Baron Omatsuri and the Secret Island",
    category: "Movie",
    director: "Mamoru Hosoda",
    duration: "92 minutes",
    yearPublished: 2005,
    rating: 4.6,
    genres: ["Adventure", "Mystery", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/LSf3hNw/One-Piece-Baron-Omatsuri-and-the-Secret-Island.jpg",
      "https://i.ibb.co.com/CwFYCzg/One-Piece-Baron-Omatsuri-and-the-Secret-Island1.jpg",
    ],
    description:
      "Lured to a mysterious island by the enigmatic Baron Omatsuri, the Straw Hats find themselves embroiled in a series of challenges designed to test their unity and loyalty. As secrets unfold, the crew must confront their inner fears and insecurities to escape the Baron's grip. This haunting and psychological adventure showcases the depth of their bonds and the strength they draw from each other.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 2300000,
  },
  {
    title: "One Piece Chopper's Kingdom in the Strange Animal Island",
    category: "Movie",
    director: "Junji Shimizu",
    duration: "56 minutes",
    yearPublished: 2002,
    rating: 4.3,
    genres: ["Adventure", "Fantasy", "Comedy"],
    imageUrl: [
      "https://i.ibb.co.com/Vw5Gcq1/One-Piece-Chopper-s-Kingdom-in-the-Strange-Animal-Island.jpg",
      "https://i.ibb.co.com/ctt8Y9v/One-Piece-Chopper-s-Kingdom-in-the-Strange-Animal-Island1.jpg",
      "https://i.ibb.co.com/Zdpqhx2/One-Piece-Chopper-s-Kingdom-in-the-Strange-Animal-Island2.jpg",
    ],
    description:
      "When Chopper is mistaken for a king on a mysterious island filled with bizarre animals, he finds himself in the midst of an epic adventure. The crew must band together to protect their friend and unravel the island's secrets, leading to heartfelt moments and hilarious encounters. This movie highlights Chopper’s character and the crew's camaraderie in a unique setting.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 1800000,
  },
  {
    title: "One Piece Clockwork Island Adventure",
    category: "Movie",
    director: "Kōnosuke Uda",
    duration: "60 minutes",
    yearPublished: 2001,
    rating: 4.4,
    genres: ["Adventure", "Action", "Comedy"],
    imageUrl: [
      "https://i.ibb.co.com/wB11jCZ/One-Piece-Clockwork-Island-Adventure.jpg",
      "https://i.ibb.co.com/bsGFrR6/One-Piece-Clockwork-Island-Adventure1.jpg",
      "https://i.ibb.co.com/wh8RXNT/One-Piece-Clockwork-Island-Adventure2.jpg",
    ],
    description:
      "The Straw Hat Pirates find themselves on Clockwork Island, where they must confront a mechanical menace led by the villainous Baron Kuro. As the crew battles mechanical foes and overcomes various challenges, they also uncover the island's secrets. The film emphasizes teamwork, courage, and the spirit of adventure, showcasing the crew's resilience against overwhelming odds.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 1500000,
  },
  {
    title: "One Piece Dead End Adventure",
    category: "Movie",
    director: "Kōnosuke Uda",
    duration: "70 minutes",
    yearPublished: 2003,
    rating: 4.5,
    genres: ["Adventure", "Action", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/G7sM6sH/One-Piece-Dead-End-Adventure.jpg",
      "https://i.ibb.co.com/q1gQSq1/One-Piece-Dead-End-Adventure1.jpg",
    ],
    description:
      "The Straw Hats enter the legendary Dead End Race, a perilous competition where pirates risk their lives for treasure. The stakes are high as they face dangerous rivals and treacherous waters. With thrilling battles and unexpected alliances, this movie showcases the crew's determination and adventurous spirit as they strive to emerge victorious.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 1600000,
  },
  {
    title: "One Piece Episode of Chopper Plus: Bloom in the Winter",
    category: "Movie",
    director: "Munehisa Sakai",
    duration: "100 minutes",
    yearPublished: 2011,
    rating: 4.6,
    genres: ["Adventure", "Comedy", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/ZBCNsZp/One-Piece-Episode-of-Chopper-Plus-Bloom-in-the-Winter.jpg",
      "https://i.ibb.co.com/VYsQSdt/One-Piece-Episode-of-Chopper-Plus-Bloom-in-the-Winter1.jpg",
    ],
    description:
      "This special episode revisits the story of Chopper as he battles to save his friends from the effects of a mysterious flower. The narrative blends humor with heartfelt moments as the crew bands together to support their beloved doctor. With its charming animation and emotional depth, this special emphasizes the importance of friendship and sacrifice.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 1800000,
  },
  {
    title: "One Piece Episode of Luffy: Adventure on Hand Island",
    category: "Movie",
    director: "Kōnosuke Uda",
    duration: "45 minutes",
    yearPublished: 2012,
    rating: 4.3,
    genres: ["Adventure", "Action", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/3TgLsXt/One-Piece-Episode-of-Luffy-Adventure-on-Hand-Island.jpg",
      "https://i.ibb.co.com/WzD2R7L/One-Piece-Episode-of-Luffy-Adventure-on-Hand-Island1.jpg",
    ],
    description:
      "In this special, Luffy and the crew navigate the treacherous Hand Island, known for its unique challenges and threats. As they face off against formidable foes and solve puzzles to uncover the island's secrets, the crew must rely on their unique abilities and unwavering friendship. This episode blends action with a lighthearted tone, reflecting the spirit of the Straw Hat Pirates.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 1200000,
  },
  {
    title: "One Piece Film Gold",
    category: "Movie",
    director: "Hiroaki Miyamoto",
    duration: "120 minutes",
    yearPublished: 2016,
    rating: 4.8,
    genres: ["Action", "Adventure", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/m6md6Rj/One-Piece-Film-Gold.jpg",
      "https://i.ibb.co.com/0s5KvvX/One-Piece-Film-Gold1.jpg",
      "https://i.ibb.co.com/fMJn556/One-Piece-Film-Gold2.jpg",
    ],
    description:
      "In the glittering entertainment city of Gran Tesoro, ruled by the powerful Gild Tesoro, the Straw Hat Pirates face their most opulent challenge. Drawn into a world of luxury and corruption, they must rely on their courage and unity to take down the golden empire. This action-packed adventure highlights the crew’s resilience and Luffy’s relentless pursuit of freedom.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 3100000,
  },
  {
    title: "One Piece Film Red",
    category: "Movie",
    director: "Goro Taniguchi",
    duration: "115 minutes",
    yearPublished: 2022,
    rating: 4.9,
    genres: ["Action", "Adventure", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/PY09X4g/One-Piece-Film-Red.jpg",
      "https://i.ibb.co.com/85qDWZX/One-Piece-Film-Red1.jpg",
      "https://i.ibb.co.com/XLW5Yy3/One-Piece-Film-Red2.jpg",
    ],
    description:
      "In this recent installment, Luffy and the crew confront a powerful figure from Shanks' past. Filled with thrilling battles and emotional revelations, the film dives deep into the history of the Red-Haired Pirates and Luffy's journey as a pirate. The movie combines action, intrigue, and heartfelt moments, celebrating the legacy of the series and its beloved characters.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 3500000,
  },
  {
    title: "One Piece Film Z",
    category: "Movie",
    director: "Takeshi Furukawa",
    duration: "108 minutes",
    yearPublished: 2012,
    rating: 4.7,
    genres: ["Action", "Adventure", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/0fhDhdM/One-Piece-Film-Z.jpg",
      "https://i.ibb.co.com/CmqpNVk/One-Piece-Film-Z1.jpg",
      "https://i.ibb.co.com/gr7jryc/One-Piece-Film-Z2.jpg",
    ],
    description:
      "The Straw Hats face off against former Marine Admiral Zephyr, who has declared war on the pirates. With breathtaking battles and moral dilemmas, the film explores the themes of justice and freedom. As Luffy and his friends strive to protect their ideals and confront Zephyr's vendetta, the movie showcases the strength of their convictions and friendships.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 2500000,
  },
  {
    title: "One Piece Heart of Gold",
    category: "Movie",
    director: "Hiroaki Miyamoto",
    duration: "90 minutes",
    yearPublished: 2016,
    rating: 4.6,
    genres: ["Adventure", "Fantasy", "Comedy"],
    imageUrl: [
      "https://i.ibb.co.com/PGZ8qqh/One-Piece-Heart-of-Gold.jpg",
      "https://i.ibb.co.com/2cRDqXY/One-Piece-Heart-of-Gold1.jpg",
    ],
    description:
      "The Straw Hat Pirates embark on a quest to find the legendary treasure known as Heart of Gold. With a mix of adventure, humor, and emotional moments, the film highlights the crew's bond as they navigate through challenges and face off against a notorious foe. The heartwarming narrative and stunning animation make this a must-watch for fans.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 2000000,
  },
  {
    title: "One Piece Stampede",
    category: "Movie",
    director: "Takashi Otsuka",
    duration: "101 minutes",
    yearPublished: 2019,
    rating: 4.8,
    genres: ["Action", "Adventure"],
    imageUrl: [
      "https://i.ibb.co.com/mJ8phvm/One-Piece-Stampede.jpg",
      "https://i.ibb.co.com/jRHhsZs/One-Piece-Stampede1.jpg",
      "https://i.ibb.co.com/gTyHws7/One-Piece-Stampede2.jpg",
    ],
    description:
      "At the Pirate Expo, the Straw Hat Pirates find themselves caught in a battle against formidable opponents, all vying for the ultimate treasure left by Gol D. Roger. With intense action and cameo appearances from various characters throughout the series, this film is a celebration of the One Piece universe and the adventurous spirit that unites all pirates.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 4000000,
  },
  {
    title: "One Piece Strong World",
    category: "Movie",
    director: "Munehisa Sakai",
    duration: "114 minutes",
    yearPublished: 2009,
    rating: 4.7,
    genres: ["Action", "Adventure"],
    imageUrl: [
      "https://i.ibb.co.com/8sm0WTb/One-Piece-Strong-World.jpg",
      "https://i.ibb.co.com/zJzjWdh/One-Piece-Strong-World1.jpg",
    ],
    description:
      "The legendary pirate Shiki returns and kidnaps Nami, leading the Straw Hats on a daring rescue mission. Strong World features high-stakes battles, remarkable landscapes, and showcases the crew's fierce loyalty to each other. This movie, penned by One Piece creator Eiichiro Oda, is a fan-favorite filled with exhilarating action and iconic character moments.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 2700000,
  },
  {
    title: "One Piece The Cursed Holy Sword",
    category: "Movie",
    director: "Goro Taniguchi",
    duration: "90 minutes",
    yearPublished: 2004,
    rating: 4.3,
    genres: ["Adventure", "Action", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/Gs9RSG1/One-Piece-The-Cursed-Holy-Sword.jpg",
      "https://i.ibb.co.com/m0cbKN2/One-Piece-The-Cursed-Holy-Sword1.jpg",
    ],
    description:
      "The Straw Hats encounter a cursed sword that brings chaos to its wielders. As they fight against a group of pirates led by the sword’s dark power, they must also confront their own fears and pasts. This movie combines adventure and fantasy, exploring themes of bravery and redemption while showcasing the crew's dynamic.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 1900000,
  },
  {
    title: "One Piece The Movie",
    category: "Movie",
    director: "Goro Taniguchi",
    duration: "60 minutes",
    yearPublished: 2000,
    rating: 4.2,
    genres: ["Adventure", "Action"],
    imageUrl: [
      "https://i.ibb.co.com/bdLbZzq/One-Piece-The-Movie.jpg",
      "https://i.ibb.co.com/0X3dyJW/One-Piece-The-Movie1.jpg",
      "https://i.ibb.co.com/SR3KGg0/One-Piece-The-Movie2.jpg",
    ],
    description:
      "In their first cinematic adventure, the Straw Hat Pirates take on the villainous pirate, El Drago, who aims to steal the treasure of the island. Filled with action, humor, and camaraderie, this film sets the stage for the crew’s epic journey and introduces fans to the world of One Piece on a grand scale.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 2200000,
  },
  {
    title: "One Piece: The Giant Mechanical Soldier of Karakuri Castle",
    category: "Movie",
    director: "Kōnosuke Uda",
    duration: "94 minutes",
    yearPublished: 2006,
    rating: 6.7,
    genres: ["Adventure", "Action", "Comedy"],
    imageUrl: [
      "https://i.ibb.co.com/Pjbftmq/One-Piece-The-Giant-Mechanical-Soldier-of-Karakuri-Castle.jpg",
      "https://i.ibb.co.com/nn3Y2VS/One-Piece-The-Giant-Mechanical-Soldier-of-Karakuri-Castle1.jpg",
    ],
    description:
      "The Straw Hat Pirates journey to a mysterious island in search of treasure rumored to be hidden in the legendary Golden Crown. There, they encounter the Giant Mechanical Soldier, strange creatures, and traps galore. This lighthearted adventure showcases Luffy and his crew's comedic misadventures and bravery.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 1100000,
  },
  {
    title: "Patema Inverted",
    category: "Movie",
    director: "Yasuhiro Yoshiura",
    duration: "98 minutes",
    yearPublished: 2013,
    rating: 7.7,
    genres: ["Science Fiction", "Adventure", "Drama"],
    imageUrl: [
      "https://i.ibb.co.com/ykkx70C/Patema-Inverted.jpg",
      "https://i.ibb.co.com/p094SSv/Patema-Inverted2.jpg",
    ],
    description:
      "In a world where gravity is inverted, Patema, a girl from an underground society, meets a boy named Age. Together, they embark on a journey that challenges their understanding of gravity and the world around them. This film beautifully explores themes of perspective, friendship, and the quest for freedom.",
    language: "Japanese",
    publisher: "Kino Films",
    totalViews: 800000,
  },
  {
    title: "Spirited Away",
    category: "Movie",
    director: "Hayao Miyazaki",
    duration: "125 minutes",
    yearPublished: 2001,
    rating: 8.6,
    genres: ["Fantasy", "Adventure", "Family"],
    imageUrl: [
      "https://i.ibb.co.com/8BtqJ0L/Spirited-Away.jpg",
      "https://i.ibb.co.com/yRQYNYW/Spirited-Away1.jpg",
      "https://i.ibb.co.com/MR6CkZV/Spirited-Away2.jpg",
    ],
    description:
      "Chihiro, a young girl, finds herself trapped in a mysterious spirit world after her parents are transformed into pigs. To save them and return home, she must navigate the challenges of the spirit realm, working in a bathhouse run by witches and befriending various creatures. This Oscar-winning film showcases Miyazaki's imaginative storytelling and stunning animation.",
    language: "Japanese",
    publisher: "Studio Ghibli",
    totalViews: 25000000,
  },
  {
    title: "Summer Ghost",
    category: "Movie",
    director: "Liden Films",
    duration: "40 minutes",
    yearPublished: 2021,
    rating: 7.5,
    genres: ["Drama", "Supernatural"],
    imageUrl: [
      "https://i.ibb.co.com/6B65t22/Summer-Ghost.jpg",
      "https://i.ibb.co.com/Rg84TPX/Summer-Ghost1.jpg",
      "https://i.ibb.co.com/xSCmpmd/Summer-Ghost2.jpg",
    ],
    description:
      "Three high school friends explore the legend of a summer ghost who appears to those who seek her out. As they delve into their emotions and the realities of their lives, they confront their fears and insecurities. This poignant short film captures the essence of youth and the impact of fleeting moments.",
    language: "Japanese",
    publisher: "Liden Films",
    totalViews: 500000,
  },
  {
    title: "Suzume",
    category: "Movie",
    director: "Makoto Shinkai",
    duration: "120 minutes",
    yearPublished: 2022,
    rating: 8.2,
    genres: ["Fantasy", "Adventure", "Romance"],
    imageUrl: [
      "https://i.ibb.co.com/wsrKXGW/Suzume.jpg",
      "https://i.ibb.co.com/Htxf43t/Suzume1.jpg",
      "https://i.ibb.co.com/fYTwMTK/Suzume2.jpg",
    ],
    description:
      "Suzume, a young girl, embarks on a journey to close doors that are causing disasters across Japan. Along the way, she discovers her inner strength and forms a bond with a mysterious boy. With breathtaking visuals and an emotional storyline, this film captures the beauty of personal growth and the connections we forge.",
    language: "Japanese",
    publisher: "Toho",
    totalViews: 1500000,
  },
  {
    title: "The Day Naruto Became Hokage",
    category: "Movie",
    director: "Masashi Kishimoto",
    duration: "24 minutes",
    yearPublished: 2014,
    rating: 7.9,
    genres: ["Action", "Adventure"],
    imageUrl: [
      "https://i.ibb.co.com/N2Y52ph/The-Day-Naruto-Became-Hokage.jpg",
      "https://i.ibb.co.com/Qvt8YbC/The-Day-Naruto-Became-Hokage1.jpg",
    ],
    description:
      "This special short film showcases Naruto's dream of becoming Hokage and his journey to achieve that dream. Set against the backdrop of the Hidden Leaf Village, it highlights the bonds he formed with his friends and mentors, culminating in the moment he is officially recognized as Hokage.",
    language: "Japanese",
    publisher: "Toei Animation",
    totalViews: 1200000,
  },
  {
    title: "The Garden of Words",
    category: "Movie",
    director: "Makoto Shinkai",
    duration: "46 minutes",
    yearPublished: 2013,
    rating: 7.8,
    genres: ["Drama", "Romance"],
    imageUrl: [
      "https://i.ibb.co.com/xYdTMFd/The-Garden-of-Words.jpg",
      "https://i.ibb.co.com/5TQ8xfP/The-Garden-of-Words1.jpg",
      "https://i.ibb.co.com/N1yztSJ/The-Garden-of-Words2.jpg",
    ],
    description:
      "A chance meeting in a Japanese garden between a high school student and a mysterious woman leads to a deep, emotional connection. As they meet regularly on rainy days, their bond grows, exploring themes of love, loneliness, and the beauty of fleeting moments. Shinkai's stunning animation and poignant storytelling shine in this film.",
    language: "Japanese",
    publisher: "CoMix Wave Films",
    totalViews: 3000000,
  },
  {
    title: "The Girl Who Leapt Through Time",
    category: "Movie",
    director: "Mamoru Hosoda",
    duration: "98 minutes",
    yearPublished: 2006,
    rating: 7.7,
    genres: ["Science Fiction", "Drama", "Romance"],
    imageUrl: [
      "https://i.ibb.co.com/Yy0xtcM/The-Girl-1.jpg",
      "https://i.ibb.co.com/3S2G13y/The-Girl-2.jpg",
      "https://i.ibb.co.com/wMLVscr/The-Girl.jpg",
    ],
    description:
      "When high school student Makoto discovers she can leap through time, she uses her newfound ability to improve her life. However, she soon learns that altering the past has unexpected consequences. This charming film balances lighthearted moments with deeper reflections on the importance of time and relationships.",
    language: "Japanese",
    publisher: "Kadokawa",
    totalViews: 2500000,
  },
  {
    title: "The Place Promised in Our Early Days",
    category: "Movie",
    director: "Makoto Shinkai",
    duration: "90 minutes",
    yearPublished: 2004,
    rating: 7.6,
    genres: ["Drama", "Fantasy", "Romance"],
    imageUrl: [
      "https://i.ibb.co.com/hH8kRx4/The-Place-Promised-in-Our-Early-Days.jpg",
      "https://i.ibb.co.com/B2GVmc3/The-Place-Promised-in-Our-Early-Days1.jpg",
      "https://i.ibb.co.com/Vm9LKhJ/The-Place-Promised-in-Our-Early-Days2.jpg",
    ],
    description:
      "In a world divided by war, three friends promise to build a plane and fly to a mysterious tower. As their paths diverge, the story explores themes of friendship, dreams, and the impact of choices. Shinkai's evocative visuals and emotional depth make this film a captivating experience.",
    language: "Japanese",
    publisher: "CoMix Wave Films",
    totalViews: 2000000,
  },
  {
    title: "The Tunnel to Summer, the Exit of Goodbyes",
    category: "Movie",
    director: "Tomohisa Taguchi",
    duration: "96 minutes",
    yearPublished: 2022,
    rating: 7.5,
    genres: ["Adventure", "Fantasy"],
    imageUrl: [
      "https://i.ibb.co.com/YWJt1t1/The-Tunnel-to-Summer-the-Exit-of-Goodbyes.jpg",
      "https://i.ibb.co.com/tL88pDp/The-Tunnel-to-Summer-the-Exit-of-Goodbyes1.jpg",
      "https://i.ibb.co.com/z4F8Tn3/The-Tunnel-to-Summer-the-Exit-of-Goodbyes2.jpg",
    ],
    description:
      "A magical tunnel allows those who enter it to revisit memories but at a cost. Two teenagers, facing their own challenges, enter the tunnel and confront their pasts while exploring the nature of regret and healing. This touching film blends fantasy with heartfelt storytelling.",
    language: "Japanese",
    publisher: "Fiction Factory",
    totalViews: 900000,
  },
  {
    title: "To the Forest of Firefly Lights",
    category: "Movie",
    director: "Takahiro Omori",
    duration: "45 minutes",
    yearPublished: 2011,
    rating: 8.1,
    genres: ["Fantasy", "Drama"],
    imageUrl: [
      "https://i.ibb.co.com/5M46k21/To-the-Forest-of-Firefly-Lights.jpg",
      "https://i.ibb.co.com/XD3C7x6/To-the-Forest-of-Firefly-Lights1.jpg",
    ],
    description:
      "A poignant story about a girl who meets a boy from the spirit world during summer nights. Their friendship blooms in a magical forest filled with firefly lights, exploring themes of love, loss, and the ephemeral nature of life. This film's stunning visuals and emotional depth make it a must-watch.",
    language: "Japanese",
    publisher: "Brain's Base",
    totalViews: 700000,
  },
  {
    title: "Totoro",
    category: "Movie",
    director: "Hayao Miyazaki",
    duration: "86 minutes",
    yearPublished: 1988,
    rating: 8.2,
    genres: ["Fantasy", "Family"],
    imageUrl: [
      "https://i.ibb.co.com/XCNg30B/Totoro.jpg",
      "https://i.ibb.co.com/SwthjXj/Totoro1.jpg",
      "https://i.ibb.co.com/7SD4W2H/Totoro2.jpg",
    ],
    description:
      "In this beloved classic, two sisters encounter magical creatures in the countryside, including the friendly forest spirit, Totoro. Their enchanting adventures celebrate childhood wonder, nature, and the bonds of family. With its heartwarming narrative and iconic characters, this film remains a timeless favorite.",
    language: "Japanese",
    publisher: "Studio Ghibli",
    totalViews: 30000000,
  },
  {
    title: "Weathering with You",
    category: "Movie",
    director: "Makoto Shinkai",
    duration: "112 minutes",
    yearPublished: 2019,
    rating: 7.9,
    genres: ["Fantasy", "Romance", "Drama"],
    imageUrl: [
      "https://i.ibb.co.com/nmZxmVW/Weathering-with-You.jpg",
      "https://i.ibb.co.com/FbFS0M4/Weathering-with-You1.jpg",
      "https://i.ibb.co.com/bRd2Dvt/Weathering-with-You2.jpg",
    ],
    description:
      "Hodaka, a high school boy, moves to Tokyo and meets Hina, a girl with the ability to manipulate the weather. Their relationship blossoms as they navigate the challenges of life and love amidst climate chaos. This visually stunning film highlights the importance of connection and the power of love.",
    language: "Japanese",
    publisher: "Toho",
    totalViews: 5000000,
  },
  {
    title: "Wolf Children",
    category: "Movie",
    director: "Mamoru Hosoda",
    duration: "117 minutes",
    yearPublished: 2012,
    rating: 8.1,
    genres: ["Fantasy", "Drama", "Family"],
    imageUrl: [
      "https://i.ibb.co.com/smWMsch/Wolf-Children.jpg",
      "https://i.ibb.co.com/g4vytPh/Wolf-Children-1.jpg",
    ],
    description:
      "After falling in love with a wolf man, Hana raises their two children, who can transform into wolves, amidst societal challenges. The film beautifully portrays the struggles and joys of motherhood, acceptance, and identity. Hosoda's masterful storytelling and animation create a heartwarming narrative.",
    language: "Japanese",
    publisher: "Toho",
    totalViews: 3500000,
  },
  {
    title: "Your Name",
    category: "Movie",
    director: "Makoto Shinkai",
    duration: "106 minutes",
    yearPublished: 2016,
    rating: 8.9,
    genres: ["Fantasy", "Romance", "Drama"],
    imageUrl: [
      "https://i.ibb.co.com/3sht8kM/YourName.jpg",
      "https://i.ibb.co.com/RzCRWRF/Your-Name1.jpg",
    ],
    description:
      "Two teenagers, Mitsuha and Taki, find themselves mysteriously swapping bodies, leading to a profound connection as they navigate each other's lives. As they uncover the truth behind their connection, the film explores themes of fate, time, and the bonds of love. Shinkai's breathtaking animation and storytelling make it a modern masterpiece.",
    language: "Japanese",
    publisher: "Toho",
    totalViews: 40000000,
  },
];
